### ISSUE TITLE
🐛 Bug Report: MariaDB - Count methods using OR condition in query

### ISSUE THREAD

**Issue by TorstenDittmann** [utopia-php/database#83]
### 👟 Reproduction steps

```php
$db->count(
    Audit::COLLECTION, 
    [
        new Query('column1', Query::EQUALS, ['test'],
        new Query('column2', Query::EQUALS, ['a', 'b']
    ]
);
```

Will produce following conditions in the SQL query:

```sql
  AND table_main.column1 = 'test'
  AND table_main.column2 = 'a'
  OR table_main.column2 = 'b'
```

### 👍 Expected behavior

```sql
AND table_main.column1 = 'test'
AND 
    (
        table_main.column2 = 'a'
        OR table_main.column2 = 'b'
    )
```

### 👎 Actual Behavior

see above.

Example from the complete query:

```sql
SELECT COUNT(1) as sum 
FROM (
    SELECT 1 
    FROM project_console_internal.audit table_main
    WHERE 1=1 
    AND 1=1 
    AND table_main.resource = :attribute_0_0_resource 
    AND table_main.event = :attribute_1_0_event 
    OR table_main.event = :a
) table_count
```

### 🎲 Utopia Database version

Version 0.10.x

### 🐘 PHP Version

PHP 8.0.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/utopia-php/database/blob/main/CODE_OF_CONDUCT.md)

**Comment by kodumbeats** [comment]
```
```
